apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-postgres-test-config
  labels:
    app: auth-postgres-test
data:
  POSTGRES_DB: auth-test
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
