name: auth-pull-request

on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "auth/**"

defaults:
  run:
    working-directory: auth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: yarn && yarn lint && yarn test
      - run: docker-compose down
