name: client-pull-request

on:
  pull_request:
    paths:
      - "client/**"

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn lint

